namespace F4Utils.Campaign.F4Structs
{
    public enum Rwr_Symbols
    {
        RWRSYM_NONE = 0,
        RWRSYM_UNKNOWN = 1,
        RWRSYM_ADVANCED_INTERCEPTOR = 2,
        RWRSYM_BASIC_INTERCEPTOR = 3,
        RWRSYM_ACTIVE_MISSILE = 4,
        RWRSYM_HAWK = 5,
        RWRSYM_PATRIOT = 6,
        RWRSYM_SA2 = 7,
        RWRSYM_SA3 = 8,
        RWRSYM_SA4 = 9,
        RWRSYM_SA5 = 10,
        RWRSYM_SA6 = 11,
        RWRSYM_SA8 = 12,
        RWRSYM_SA9 = 13,
        RWRSYM_SA10 = 14,
        RWRSYM_SA13 = 15,
        RWRSYM_AAA = 16,
        RWRSYM_SEARCH = 17,
        RWRSYM_NAVAL = 18,
        RWRSYM_CHAPARAL = 19,
        RWRSYM_SA15 = 20,
        RWRSYM_NIKE = 21,

        RWRSYM_A1 = 22,
        RWRSYM_A2 = 23,
        RWRSYM_A3 = 24,

        RWRSYM_PDOT = 25,
        RWRSYM_PSLASH = 26,

        RWRSYM_UNK1 = 27,
        RWRSYM_UNK2 = 28,
        RWRSYM_UNK3 = 29,

        RWRSYM_KSAM = 30,

        RWRSYM_V4 = 32,
        RWRSYM_V5 = 33,
        RWRSYM_V6 = 34,
        RWRSYM_V14 = 35,
        RWRSYM_V15 = 36,
        RWRSYM_V16 = 37,
        RWRSYM_V18 = 38,
        RWRSYM_V19 = 39,
        RWRSYM_V20 = 40,
        RWRSYM_V21 = 41,
        RWRSYM_V22 = 42,
        RWRSYM_V23 = 43,
        RWRSYM_V25 = 44,
        RWRSYM_V27 = 45,
        RWRSYM_V29 = 46,
        RWRSYM_V30 = 47,
        RWRSYM_V31 = 48,
        RWRSYM_VP = 49,
        RWRSYM_VPD = 50,
        RWRSYM_VA = 51,
        RWRSYM_VB = 52,
        RWRSYM_VS = 53,

        RWRSYM_Aa = 54,
        RWRSYM_Ab = 55,
        RWRSYM_Ac = 56,
        RWRSYM_MIB_F_S = 57,
        RWRSYM_MIB_F_A = 58,
        RWRSYM_MIB_F_M = 59,
        RWRSYM_MIB_F_U = 60,
        RWRSYM_MIB_F_BW = 61,
        RWRSYM_MIB_BW_S = 62,
        RWRSYM_MIB_BW_A = 63,
        RWRSYM_MIB_BW_M = 64,

    }
}