namespace SoundCardRWR
{
    public enum ChannelMask : uint
    {
        SPEAKER_FRONT_LEFT = 0x1,
        SPEAKER_FRONT_RIGHT = 0x2,
        SPEAKER_FRONT_CENTER = 0x4,
        SPEAKER_LOW_FREQUENCY = 0x8,
        SPEAKER_BACK_LEFT = 0x10,
        SPEAKER_BACK_RIGHT = 0x20,
        SPEAKER_FRONT_LEFT_OF_CENTER = 0x40,
        SPEAKER_FRONT_RIGHT_OF_CENTER = 0x80,
        SPEAKER_BACK_CENTER = 0x100,
        SPEAKER_SIDE_LEFT = 0x200,
        SPEAKER_SIDE_RIGHT = 0x400,
        SPEAKER_TOP_CENTER = 0x800,
        SPEAKER_TOP_FRONT_LEFT = 0x1000,
        SPEAKER_TOP_FRONT_CENTER = 0x2000,
        SPEAKER_TOP_FRONT_RIGHT = 0x4000,
        SPEAKER_TOP_BACK_LEFT = 0x8000,
        SPEAKER_TOP_BACK_CENTER = 0x10000,
        SPEAKER_TOP_BACK_RIGHT = 0x20000,
        SPEAKER_RESERVED = 0x7FFC0000,
        SPEAKER_ALL = 0x80000000,
    }
    public enum SurroundChannelMask : uint
    {
        KSAUDIO_SPEAKER_MONO = ChannelMask.SPEAKER_FRONT_CENTER,
        KSAUDIO_SPEAKER_STEREO = ChannelMask.SPEAKER_FRONT_LEFT | ChannelMask.SPEAKER_FRONT_RIGHT,
        KSAUDIO_SPEAKER_QUAD = ChannelMask.SPEAKER_FRONT_LEFT | ChannelMask.SPEAKER_FRONT_RIGHT | ChannelMask.SPEAKER_BACK_LEFT | ChannelMask.SPEAKER_BACK_RIGHT,
        KSAUDIO_SPEAKER_SURROUND = ChannelMask.SPEAKER_FRONT_LEFT | ChannelMask.SPEAKER_FRONT_RIGHT | ChannelMask.SPEAKER_FRONT_CENTER | ChannelMask.SPEAKER_BACK_CENTER,
        KSAUDIO_SPEAKER_5POINT1 = ChannelMask.SPEAKER_FRONT_LEFT | ChannelMask.SPEAKER_FRONT_RIGHT | ChannelMask.SPEAKER_FRONT_CENTER | ChannelMask.SPEAKER_LOW_FREQUENCY | ChannelMask.SPEAKER_BACK_LEFT | ChannelMask.SPEAKER_BACK_RIGHT,
        KSAUDIO_SPEAKER_7POINT1 = ChannelMask.SPEAKER_FRONT_LEFT | ChannelMask.SPEAKER_FRONT_RIGHT | ChannelMask.SPEAKER_FRONT_CENTER | ChannelMask.SPEAKER_LOW_FREQUENCY | ChannelMask.SPEAKER_BACK_LEFT | ChannelMask.SPEAKER_BACK_RIGHT | ChannelMask.SPEAKER_FRONT_LEFT_OF_CENTER | ChannelMask.SPEAKER_FRONT_RIGHT_OF_CENTER
    }
    
}
