namespace SimLinkup.HardwareSupport.Powell
{
    internal enum Symbols : byte
    {
        Zero = 0,
        One = 1,
        Two = 2,
        Three = 3,
        Four = 4,
        Five = 5,
        Six = 6,
        Seven = 7,
        Eight = 8,
        Nine = 9,
        A = 10,
        B = 11,
        C = 12,
        D = 13,
        E = 14,
        H = 15,
        M = 16,
        N = 17,
        P = 18,
        S = 19,
        U = 20,
        Dot = 21,
        Underscore = 22,
        Hat = 23,
        Ship = 24,
        AdvancedInterceptor = 25,
        BasicInterceptor = 26,
        Circle = 27,
        Diamond = 28,
        Box1 = 29,
        Box2 = 30,
        Box3 = 31,
        BlinkBit = 32,
        VerticalLine = 33,
        F = 34,
        G = 35,
        I = 36,
        J = 37,
        K = 38,
        L = 39,
        O = 40,
        Q = 41,
        R = 42,
        T = 43,
        V = 44,
        W = 45,
        X = 46,
        Y = 47,
        Z = 48,
        LeftBracket = 49,
        Backslash = 50,
        RightBracket = 51,
        BackTick = 52,
        LowerCaseA = 53,
        LowerCaseB = 54,
        LowerCaseC = 55
    }
}