//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F16CPD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartWhenLaunched {
            get {
                return ((bool)(this["StartWhenLaunched"]));
            }
            set {
                this["StartWhenLaunched"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaunchAtWindowsStartup {
            get {
                return ((bool)(this["LaunchAtWindowsStartup"]));
            }
            set {
                this["LaunchAtWindowsStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAsClient {
            get {
                return ((bool)(this["RunAsClient"]));
            }
            set {
                this["RunAsClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAsServer {
            get {
                return ((bool)(this["RunAsServer"]));
            }
            set {
                this["RunAsServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerIPAddress {
            get {
                return ((string)(this["ServerIPAddress"]));
            }
            set {
                this["ServerIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21153")]
        public string ServerPortNum {
            get {
                return ((string)(this["ServerPortNum"]));
            }
            set {
                this["ServerPortNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int PollingFrequencyMillis {
            get {
                return ((int)(this["PollingFrequencyMillis"]));
            }
            set {
                this["PollingFrequencyMillis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Threading.ThreadPriority Priority {
            get {
                return ((global::System.Threading.ThreadPriority)(this["Priority"]));
            }
            set {
                this["Priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CpdWindowX {
            get {
                return ((int)(this["CpdWindowX"]));
            }
            set {
                this["CpdWindowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CpdWindowY {
            get {
                return ((int)(this["CpdWindowY"]));
            }
            set {
                this["CpdWindowY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int CpdWindowWidth {
            get {
                return ((int)(this["CpdWindowWidth"]));
            }
            set {
                this["CpdWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int CpdWindowHeight {
            get {
                return ((int)(this["CpdWindowHeight"]));
            }
            set {
                this["CpdWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShutoffIfFalconNotRunning {
            get {
                return ((bool)(this["ShutoffIfFalconNotRunning"]));
            }
            set {
                this["ShutoffIfFalconNotRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlBindings {
            get {
                return ((string)(this["ControlBindings"]));
            }
            set {
                this["ControlBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Brightness {
            get {
                return ((int)(this["Brightness"]));
            }
            set {
                this["Brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayNorthAsThreeSixZero {
            get {
                return ((bool)(this["DisplayNorthAsThreeSixZero"]));
            }
            set {
                this["DisplayNorthAsThreeSixZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AsiLockoutSpeedKnots {
            get {
                return ((int)(this["AsiLockoutSpeedKnots"]));
            }
            set {
                this["AsiLockoutSpeedKnots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAsiLockoutSpeed {
            get {
                return ((bool)(this["UseAsiLockoutSpeed"]));
            }
            set {
                this["UseAsiLockoutSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RotateNoneFlipNone")]
        public global::Common.Drawing.RotateFlipType Rotation {
            get {
                return ((global::Common.Drawing.RotateFlipType)(this["Rotation"]));
            }
            set {
                this["Rotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FastCourseAndHeadingAdjustSpeed {
            get {
                return ((int)(this["FastCourseAndHeadingAdjustSpeed"]));
            }
            set {
                this["FastCourseAndHeadingAdjustSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayVerticalVelocityInDecimalThousands {
            get {
                return ((bool)(this["DisplayVerticalVelocityInDecimalThousands"]));
            }
            set {
                this["DisplayVerticalVelocityInDecimalThousands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgradeNeeded {
            get {
                return ((bool)(this["SettingsUpgradeNeeded"]));
            }
            set {
                this["SettingsUpgradeNeeded"] = value;
            }
        }
    }
}
