using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Falcon BMS Shared Memory Reader")]
[assembly: AssemblyDescription("Falcon BMS Shared Memory Reader")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Falcon BMS Shared Memory Reader")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: Guid("7cd071e9-56f0-4e7a-b261-622c2bcbb44e")]
[assembly: AssemblyVersion("4.35.0.0")]
[assembly: AssemblyFileVersion("4.35.0.0")]
