
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.BitBlt(System.IntPtr,System.Int32,System.Int32,System.Int32,System.Int32,System.IntPtr,System.Int32,System.Int32,System.Int32)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.CreateCompatibleBitmap(System.IntPtr,System.Int32,System.Int32)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.CreateCompatibleDC(System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.DeleteDC(System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.DeleteObject(System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.GetDC(System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.GetDesktopWindow~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.GetForegroundWindow~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.GetWindowDC(System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.MapVirtualKey(System.UInt32,Common.Win32.NativeMethods.MAPVK_MAPTYPES)~System.UInt32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.MapVirtualKeyEx(System.UInt32,Common.Win32.NativeMethods.MAPVK_MAPTYPES,System.IntPtr)~System.UInt32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.PathCanonicalize(System.Text.StringBuilder,System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.PathCompactPathEx(System.Text.StringBuilder,System.String,System.Int32,System.Int32)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.PathFindSuffixArray(System.String,System.String[],System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.PathIsContentType(System.String,System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.PathMakePretty(System.Text.StringBuilder)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.ReleaseDC(System.IntPtr,System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.NativeMethods.SelectObject(System.IntPtr,System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0097:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.KeyAndMouseFunctions.MouseMoveAbsolute(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0097:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.KeyAndMouseFunctions.MouseMoveRelative(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "CC0097:You have missing/unexistent parameters in Xml Docs", Justification = "<Pending>", Scope = "member", Target = "~M:Common.Win32.KeyAndMouseFunctions.MouseWheelMove(System.Int32)")]