namespace LightningGauges.Renderers.F16.AzimuthIndicator
{
    public enum ThreatSymbols
    {
        RWRSYM_NONE = 0, // nothing
        RWRSYM_UNKNOWN = 1, // U
        RWRSYM_ADVANCED_INTERCEPTOR = 2, //not used
        RWRSYM_BASIC_INTERCEPTOR = 3, //not used
        RWRSYM_ACTIVE_MISSILE = 4, //M
        RWRSYM_HAWK = 5, //H
        RWRSYM_PATRIOT = 6, //P
        RWRSYM_SA2 = 7, //2
        RWRSYM_SA3 = 8, //3
        RWRSYM_SA4 = 9, //4
        RWRSYM_SA5 = 10, //5
        RWRSYM_SA6 = 11, //6
        RWRSYM_SA8 = 12, //8
        RWRSYM_SA9 = 13, //9
        RWRSYM_SA10 = 14, //10
        RWRSYM_SA13 = 15, //13
        RWRSYM_AAA = 16, //A or S alternating
        RWRSYM_SEARCH = 17, //S
        RWRSYM_NAVAL = 18, //boat symbol
        RWRSYM_CHAPARAL = 19, //C
        RWRSYM_SA15 = 20, //15 or M alternating
        RWRSYM_NIKE = 21, //N
        RWRSYM_A1 = 22, //A with a single dot under it
        RWRSYM_A2 = 23, //A with two dots under it
        RWRSYM_A3 = 24, //A with three dots under it
        RWRSYM_PDOT = 25, //P with a dot under it
        RWRSYM_PSLASH = 26, //P with a vertical bar after it
        RWRSYM_UNK1 = 27, //U with one dot under it
        RWRSYM_UNK2 = 28, //U with two dots under it
        RWRSYM_UNK3 = 29, //U with three dots under it
        RWRSYM_KSAM = 30, //C
        RWRSYM_V1 = 31, //1
        RWRSYM_V4 = 32, //4
        RWRSYM_V5 = 33, //5
        RWRSYM_V6 = 34, //6
        RWRSYM_V14 = 35, //14
        RWRSYM_V15 = 36, //15
        RWRSYM_V16 = 37, //16
        RWRSYM_V18 = 38, //18
        RWRSYM_V19 = 39, //19
        RWRSYM_V20 = 40, //20
        RWRSYM_V21 = 41, //21
        RWRSYM_V22 = 42, //22
        RWRSYM_V23 = 43, //23
        RWRSYM_V25 = 44, //25
        RWRSYM_V27 = 45, //27
        RWRSYM_V29 = 46, //29
        RWRSYM_V30 = 47, //30
        RWRSYM_V31 = 48, //31
        RWRSYM_VP = 49, //P
        RWRSYM_VPD = 50, //PD
        RWRSYM_VA = 51, //A
        RWRSYM_VB = 52, //B
        RWRSYM_VS = 53, //S
        RWRSYM_Aa = 54, //A with a vertical bar after it
        RWRSYM_Ab = 55, //A with vertical bars before and after it
        RWRSYM_Ac = 56, //A with vertical bars before and after it and one through the middle
        RWRSYM_MIB_F_S = 57, //F or S alternating
        RWRSYM_MIB_F_A = 58, //F or A alternating
        RWRSYM_MIB_F_M = 59, //F or M alternating
        RWRSYM_MIB_F_U = 60, //F or U alternating
        RWRSYM_MIB_F_BW = 61, //F or basic interceptor shape
        RWRSYM_MIB_BW_S = 62, //S or basic interceptor shape
        RWRSYM_MIB_BW_A = 63, //A or basic interceptor shape
        RWRSYM_MIB_BW_M = 64 //M or basic interceptor shape
    }
}